apiVersion: skaffold/v2alpha1
kind: Config
build:
    local:
        push: false
    artifacts:
        - image: pablodu92/docker-fibonacci-client
          context: client
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
                - '***/*.js'
                - '***/*.css'
                - '***/*.html'
        - image: pablodu92/docker-fibonacci-server
          context: server
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
                - '***/*.js'
        - image: pablodu92/docker-fibonacci-worker
          context: worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
                - '***/*.js'
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
            - k8s/server-deployment.yaml
            - k8s/worker-deployment.yaml
            - k8s/server-cluster-ip-service.yaml
            - k8s/client-cluster-ip-service.yaml
